ShoppingList.Web/Controllers/ListItemsController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using ShoppingList.Data.Models;
using ShoppingList.Models;
using ShoppingList.Services;
using System;
using System.Data;
using System.Linq;
using System.Web.Mvc;

namespace ShoppingList.Web.Controllers
{
    [Authorize]
    public class ListItemsController : Controller
    {
        private ShoppingListDbContext db = new ShoppingListDbContext();
        private int? ID;

        // GET: ListItems
        // GET: Customer
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {

            if (TempData.ContainsKey("ID"))
            {
                ID = TempData["ID"] as int?;
            }
            //else
            //{
            //    ID = 0;
            //}

            var service = CreateService();

            var items = service.GetItems();


            ViewBag.CurrentSort = sortOrder;
            ViewBag.ItemSortParm = String.IsNullOrEmpty(sortOrder) ? "item_desc" : "";
            ViewBag.PrioritySortParm = sortOrder == "Priority" ? "priority_desc" : "Priority";            


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(s => s.Contents.Contains(searchString));
   
            }
            switch (sortOrder)
            {
                case "item_desc":
                    items = items.OrderByDescending(s => s.Contents);
                    break;
                case "Priority":
                    items = items.OrderBy(s => s.Priority);
                    break;
                case "priority_desc":
                    items = items.OrderByDescending(s => s.Priority);
                    break;
                default:
                    items = items.OrderBy(s => s.Contents);
                    break;
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);

            TempData["ID"] = ID;

            return View(items.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Index()
        {
            return RedirectToAction("Index", "ShoppingList");
        }

        // GET: ListItems/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ShoppingListItem shoppingListItem = db.ShoppingListItems.Find(id);
        //    if (shoppingListItem == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(shoppingListItem);
        //}

        // GET: ListItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ListItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ShoppingItemCreate model)
        {


            if (!ModelState.IsValid) return View(model);

            var service = CreateService();

            if (service.CreateItem(model))
            {
                TempData["SaveResult2"] = "Your item was successfully created!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your item could not be created.");

            TempData["ID"] = ID;

            return RedirectToAction("Index");

        }

        // GET: ListItems/Edit/5
        public ActionResult Edit(int id)
        {

            var service = CreateService();
            var detail = service.GetNoteById(id);

            var model =
                new ShoppingItemEdit
                {
                    ShoppingListItemID = detail.ShoppingListItemID,
                    Contents = detail.Contents,
                    Priority = detail.Priority,
                    Note = detail.Note
                };

            TempData["ID"] = ID;

            return View(model);
        }

        // POST: ListItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ShoppingItemEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.ShoppingListItemID != id)
            {
                ModelState.AddModelError("", "ID Mismatch");
                return View(model);
            }

            var service = CreateService();


            if (service.UpdateItem(model))
            {
                TempData["SaveResult2"] = "Your list item was successfully updated!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your list item could not be updated.");

            ID = TempData["ID"] as int?;

            return View(model);
        }

        // GET: ShoppingList/Delete/5
        public ActionResult Delete(int id)
        {
            var service = CreateService();
            var model = service.GetNoteById(id);
            TempData["ID"] = ID;
            return View(model);
        }

        // POST: ShoppingList/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            var service = CreateService();
            TempData["ID"] = ID;

            if (service.DeleteItem(id))
            {
                TempData["SaveResult"] = "Your item was successfully deleted.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your item could not be deleted!");

             

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private ShoppingListItemService CreateService()
        {

            ID = TempData["ID"] as int?;
            var userId = Guid.Parse(User.Identity.GetUserId());
            var listId = (int)ID;
            var service = new ShoppingListItemService(userId, listId);
            return service;
        }
    }
}

ShoppingList.Web/Views/ListItems/Create.cshtml
@model ShoppingList.Models.ShoppingItemCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Create Shopping List Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contents, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Priority, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShoppingList.Web/Views/ListItems/Delete.cshtml
@model ShoppingList.Models.ShoppingItemEdit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ShoppingListItem</h4>
    <hr />
    <dl class="dl-horizontal">
        

        
        <dt>
            Contents
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contents)
        </dd>

        <dt>
           Priority
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            Note
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.IsChecked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsChecked)
        </dd>*@

       

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShoppingList.Web/Views/ListItems/Edit.cshtml
@model ShoppingList.Models.ShoppingItemEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit Shopping List Items</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShoppingListItemID)

        <div class="form-group">
            @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contents, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Priority, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.IsChecked, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsChecked)
                    @Html.ValidationMessageFor(model => model.IsChecked, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ShoppingList.Web/Views/ListItems/Index.cshtml
@model PagedList.IPagedList<ShoppingList.Models.ShoppingItemIndex>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@if (TempData.ContainsKey("SaveResult2"))
{
    <div class="alert alert-success fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult2"]
    </div>
}

@using (Html.BeginForm("Index", "ListItems", FormMethod.Get))

{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Content", "Index", new { sortOrder = ViewBag.ItemSortParm })
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Contents)
            </th>*@
        <th>
            @Html.ActionLink("Priority", "Index", new { sortOrder = ViewBag.PriorityPram })
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.Priority)
            </th>*@
        <th>
            Note
        </th>
        <th>
            Options
        </th>

        <th></th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td class="ListTableRow">
                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="checkbox">
                                <input type="checkbox" id="checkbox" />
                                <label for="checkbox">
                                    @Html.DisplayFor(modelItem => item.Contents)
                                </label>
                            </div>
                        </li>
                    </ul>
                </div>
            </td>

            <td class="ListTableRow">
                  @Html.DisplayFor(modelItem => item.Priority)
            </td>

            <td class="ListTableRow"> @Html.DisplayFor(modelItem => item.Note) </td>

            @*<td>
                    @Html.DisplayFor(modelItem => item.IsChecked, new { Id = item.ShoppingListItemID })
                </td>*@
            <td class="ListTableRow">
                @Html.ActionLink("Edit", "Edit", new { id = item.ShoppingListItemID }) |
                @*@Html.ActionLink("Details", "Details", new { id=item.ShoppingListItemID }) |*@
                @Html.ActionLink("Delete", "Delete", new { id = item.ShoppingListItemID })
            </td>
        </tr>
    }

</table>
<br />

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

<div class="col-md-10">
    <input type="button" value="Back" class="btn btn-default" onclick="@("window.location.href='" + @Url.Action("Index", "ShoppingList") + "'");" />
</div>